### ISSUE TITLE
Feedback Group 1

### ISSUE THREAD

**Issue by makka3** [UBC-MDS/Mental_Health_in_TechJobs#4]
Review:

Introduce the problem that you’d like to focus on from the dataset. 

Identify the key feature(s) that you’re looking to compare between the countries
i.e. Is it the seek_help, mental_health_interview, mental_health_consequence categories or another? Maybe have that as a separate tab as well.

If a map is the visualization, more than 1 plot below it may become confusing for the user. Also, in general, more than 1 main plot on a single page may direct the user away from the objective, unless it’s extremely necessary or serves an important purpose.

Add clear titles to the tabs and the different plots. Even if they’re in question form. “Where are mental health issues most prevalent?” or something to that effect.

Add rules to the page that guides the user in the right direction to working with the visualization. For example: ‘Click on the country to see ‘this_feature’’. Also guide the user how to use the side bar optimally.

Age histogram maybe not as important as others. Mental health is an issue that’s somewhat separate from age.

Good stuff:

The use case is important. Finding the differences in mental health approaches and sentiments across different countries could be very useful in helping tackle these problems with more effective tools and methods.

The data explorer tab is a useful tool that's easy to navigate.

Plus other good stuff that we didn't have time to write here.

**Comment by MikeYuanMY** [comment]
We have included following change in milestone 3 
- removed plot under map
- include instructions 
- removed age histogram 
- renamed tab title for usability
