### ISSUE TITLE
Peer Review Feedback (Aditya, Yuwei)

### ISSUE THREAD

**Issue by adityashrm21** [UBC-MDS/Mental_Health_in_TechJobs#5]
- There can be an option for displaying all the data in the data explorer tab.
- The plot in the map tab and the plot tab are the same if we select a country which is a little redundant.
- The slider bar for selecting an age range is a useful feature to target a specific age group.
- The radio buttons provide more flexibility with the gender variable as opposed to having a single drop-down menu (where we can select only one category).
- The option of selecting multiple values for each variable is good as we are not restricted to a single option setting.
- The map marker could be used to show some useful information instead of just marking the place. The map doesn't show any useful information currently.
- The map zooms in after selecting a country to a specific small area which could be improved to show the whole country instead.
- The app fails to display any data if we deselect the countries from the country menu. This case could be handled so that the app doesn't break in this case.
- For some of the histograms, the axis values are not readable and they could be shortened or removed.

**Comment by MikeYuanMY** [comment]
- fixed the map plot and removed the redundant plot
- map marker will be pie chart to show more data
- deselect country no longer caused bugs 
- improve readability
- added more instruction on Compare Country and Data explorer tab
